name: TEST

on:
  workflow_dispatch:
    inputs:
      test:
        required: false
        type: string
        description: Build webapp Docker images
        default: '["shalom", "yafyuf"]'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test echo
      run: |
        echo ${{ toJson(github.event.inputs.test) }}
